# -*- coding: utf-8 -*-
"""entrada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KD1ncGLRkttekYMq-ZwU_1SDS08aZ_c
"""

# -----------------------------------------------------
# MODELO HOOKE TRADING – SCREENER DE ENTRY
# -----------------------------------------------------

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

# -----------------------------------------------------
# CONFIGURACIÓN
# -----------------------------------------------------
st.set_page_config(page_title="Hooke Trading Screener", layout="wide")

TICKERS = [
    "BTC-USD", "GAPB.MX", "PLTR", "SPY", "GRUMAB.MX",
    "FMTY14.MX", "IAU", "HOOD", "SOFI", "NVDA",
    "WALMEX.MX", "FUNO11.MX", "CHDRAUIB.MX",
    "QUBT", "FRES.MX", "JPM", "MCHI", "INDA"
]

st.title("📈 Modelo del Resorte de Hooke aplicado al Trading")
st.caption("Screener de proximidad al signal de entry")

# -----------------------------------------------------
# PARÁMETROS
# -----------------------------------------------------
window_ma = 10
elasticidad = 1.5

# -----------------------------------------------------
# FUNCIÓN PRINCIPAL
# -----------------------------------------------------
def analizar_ticker(ticker):
    try:
        df = yf.download(
            ticker,
            period="2y",
            interval="1d",
            progress=False,
            auto_adjust=True
        )
    except Exception:
        return None

    if df is None or df.empty or len(df) < window_ma + 5:
        return None

    # FIX CRÍTICO: columnas MultiIndex
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    if "Close" not in df.columns:
        return None

    # Medias móviles
    df["MA5"] = df["Close"].rolling(5).mean()
    df["MA10"] = df["Close"].rolling(window_ma).mean()
    df.dropna(inplace=True)

    if df.empty:
        return None

    # Modelo de Hooke
    df["x"] = df["Close"] - df["MA10"]
    threshold = df["x"].std() * elasticidad

    if threshold <= 0 or np.isnan(threshold):
        return None

    x_actual = abs(df["x"].iloc[-1])
    distancia_entry = abs(threshold - x_actual)

    # Condición de pre-entry (tendencia bajista previa)
    tendencia_ok = df["MA5"].iloc[-1] < df["MA10"].iloc[-1]

    return {
        "Ticker": ticker,
        "Precio actual": float(df["Close"].iloc[-1]),
        "|x| actual": float(x_actual),
        "Umbral": float(threshold),
        "Distancia al Entry": float(distancia_entry),
        "Tendencia OK": tendencia_ok
    }

# -----------------------------------------------------
# PROCESAMIENTO
# -----------------------------------------------------
st.info("🔄 Analizando activos...")

resultados = []

for t in TICKERS:
    data = analizar_ticker(t)
    if data is not None:
        resultados.append(data)

df_screen = pd.DataFrame(resultados)

if df_screen.empty:
    st.error("❌ No se pudieron analizar los activos.")
    st.stop()

# -----------------------------------------------------
# FILTRAR Y ORDENAR
# -----------------------------------------------------
df_screen = df_screen[df_screen["Tendencia OK"] == True]
df_screen = df_screen[df_screen["Umbral"] > 0]

if df_screen.empty:
    st.warning("⚠️ No hay activos en condición de pre-entry.")
    st.stop()

df_screen = df_screen.sort_values(
    by="Distancia al Entry",
    ascending=True
).reset_index(drop=True)

df_screen.insert(0, "Ranking", df_screen.index + 1)

# -----------------------------------------------------
# ALERTAS
# -----------------------------------------------------
df_screen["Cercania_%"] = (
    df_screen["Distancia al Entry"] / df_screen["Umbral"]
) * 100

def semaforo(x):
    if x < 5:
        return "🔴 CRÍTICO"
    elif x < 10:
        return "🟡 ATENCIÓN"
    else:
        return "🟢 LEJOS"

df_screen["Estado"] = df_screen["Cercania_%"].apply(semaforo)

criticos = df_screen[df_screen["Cercania_%"] < 5]

if not criticos.empty:
    st.error("🚨 ACTIVOS MUY PRÓXIMOS AL ENTRY 🚨")
    for _, row in criticos.iterrows():
        st.markdown(
            f"""
            **{row['Ticker']}**
            - Distancia al entry: `{row['Distancia al Entry']:.4f}`
            - Cercanía: `{row['Cercania_%']:.2f}%`
            """
        )
else:
    st.success("✅ No hay activos en zona crítica")

# -----------------------------------------------------
# TABLA FINAL
# -----------------------------------------------------
st.subheader("📋 Ranking de proximidad al Entry")

st.dataframe(
    df_screen[[
        "Ranking",
        "Ticker",
        "Precio actual",
        "|x| actual",
        "Umbral",
        "Distancia al Entry",
        "Cercania_%",
        "Estado"
    ]],
    use_container_width=True
)

st.caption("Ranking 1 = activo MÁS cercano a generar señal de entry")