# -*- coding: utf-8 -*-
"""entrada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KD1ncGLRkttekYMq-ZwU_1SDS08aZ_c
"""

# =====================================================
# MODELO HOOKE – SCREENER DE ENTRADAS (STREAMLIT)
# =====================================================

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------------------------------
# CONFIGURACIÓN
# -----------------------------------------------------
st.set_page_config(page_title="Hooke Trading Screener", layout="wide")

TICKERS = [
    "BTC-USD", "GAPB.MX", "PLTR", "SPY", "GRUMAB.MX",
    "FMTY14.MX", "IAU", "HOOD", "SOFI", "NVDA",
    "WALMEX.MX", "FUNO11.MX", "CHDRAUIB.MX",
    "QUBT", "FRES.MX", "JPM", "MCHI", "INDA"
]

st.title("📊 Modelo del Resorte de Hooke – Screener de Entradas")

# -----------------------------------------------------
# FUNCIÓN PRINCIPAL
# -----------------------------------------------------
@st.cache_data(show_spinner=False)
def analyze_ticker(ticker):
    try:
        df = yf.download(ticker, period="2y", interval="1d", progress=False)
        if df.empty:
            return None

        # Medias móviles
        df["MA5"] = df["Close"].rolling(5).mean()
        df["MA10"] = df["Close"].rolling(10).mean()
        df.dropna(inplace=True)

        # Señales
        df["Signal"] = np.where(df["MA5"] > df["MA10"], 1, 0)
        df["Crossover"] = df["Signal"].diff()

        # Modelo Hooke
        df["x"] = df["Close"] - df["MA10"]
        threshold = df["x"].std() * 1.5
        df["Exit"] = np.where(abs(df["x"]) > threshold, 1, 0)
        df["Exit_diff"] = df["Exit"].diff()

        # Entry dates
        entry_dates = df[
            (df["Exit_diff"] == -1) & (df["MA5"] < df["MA10"])
        ].index

        if len(entry_dates) == 0:
            return None

        last_entry = entry_dates[-1]
        days_from_entry = (pd.Timestamp.today().normalize() - last_entry).days

        return {
            "Ticker": ticker,
            "Último Entry": last_entry.date(),
            "Días desde Entry": days_from_entry,
            "Precio Actual": round(df["Close"].iloc[-1], 2),
            "Desviación Hooke": round(df["x"].iloc[-1], 4)
        }

    except Exception:
        return None

# -----------------------------------------------------
# EJECUCIÓN DEL SCREENER
# -----------------------------------------------------
st.subheader("🔍 Activos ordenados por cercanía al Entry")

results = []

with st.spinner("Analizando activos..."):
    for t in TICKERS:
        r = analyze_ticker(t)
        if r:
            results.append(r)

df_entries = pd.DataFrame(results)

# -----------------------------------------------------
# RESULTADOS
# -----------------------------------------------------
if not df_entries.empty:
    df_entries = df_entries.sort_values("Días desde Entry")
    st.dataframe(df_entries, use_container_width=True)

    st.caption("Menor número de días = señal más reciente")
else:
    st.warning("No se detectaron señales de entrada.")

# -----------------------------------------------------
# SELECCIÓN PARA ANÁLISIS DETALLADO
# -----------------------------------------------------
st.subheader("📈 Análisis individual")

if not df_entries.empty:
    selected = st.selectbox("Selecciona un activo:", df_entries["Ticker"])

    df = yf.download(selected, period="2y", interval="1d", progress=False)
    df["MA10"] = df["Close"].rolling(10).mean()
    df.dropna(inplace=True)

    fig, ax = plt.subplots(figsize=(14, 6))
    ax.plot(df["Close"], label="Precio", color="black")
    ax.plot(df["MA10"], label="MA10", color="orange")
    ax.scatter(
        df.index[-1],
        df["Close"].iloc[-1],
        color="red",
        label="Último precio",
        zorder=5
    )

    ax.legend()
    ax.set_title(f"{selected} – Precio y equilibrio")
    st.pyplot(fig)